<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\BeautyCenterSaaS.Application\BeautyCenterSaaS.Application.csproj" />
    <ProjectReference Include="..\BeautyCenterSaaS.Infrastructure\BeautyCenterSaaS.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
